let lightPurple = '#D400FF' //light purple
let lightYellow = '#D4FF00' // light yellow
let lightBlue = '#E6FBFF' // alt light blue
let lightRed = '#e82323'
let lightBrown = '#6d6e3a'

export let elements = [
	//
	//
	// Period 1
	//
	//
	{
		name: 'Hydrogen',
		symbol: 'H',
		atomicNumber: 1,
		period: 1,
		group: 1,
		location: 'LEFT',
		color: lightPurple,
	},
	{
		name: 'Helium',
		symbol: 'He',
		atomicNumber: 2,
		period: 1,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 2
	//
	//
	{
		name: 'Lithium',
		symbol: 'Li',
		atomicNumber: 3,
		period: 2,
		group: 1,
		color: 'orange',
		location: 'LEFT',
	},
	{
		name: 'Beryllium',
		symbol: 'Be',
		atomicNumber: 4,
		period: 2,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},
	{
		name: 'Boron',
		symbol: 'B',
		atomicNumber: 5,
		period: 2,
		group: 13,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Carbon',
		symbol: 'C',
		atomicNumber: 6,
		period: 2,
		group: 14,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Nitrogen',
		symbol: 'N',
		atomicNumber: 7,
		period: 2,
		group: 15,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Oxygen',
		symbol: 'O',
		atomicNumber: 8,
		period: 2,
		group: 16,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Fluorine',
		symbol: 'F',
		atomicNumber: 9,
		period: 2,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Neon',
		symbol: 'Ne',
		atomicNumber: 9,
		period: 2,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 3
	//
	//
	{
		name: 'Sodium',
		symbol: 'Na',
		atomicNumber: 11,
		period: 3,
		group: 1,
		location: 'LEFT',
		color: 'orange',
	},
	{
		name: 'Magnesium',
		symbol: 'Mg',
		atomicNumber: 12,
		period: 3,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},
	{
		name: 'Aluminum',
		symbol: 'Al',
		atomicNumber: 13,
		period: 3,
		group: 13,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Silicon',
		symbol: 'Si',
		atomicNumber: 14,
		period: 3,
		group: 14,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Phosphorus',
		symbol: 'P',
		atomicNumber: 15,
		period: 3,
		group: 15,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Sulfur',
		symbol: 'S',
		atomicNumber: 16,
		period: 3,
		group: 16,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Chlorine',
		symbol: 'Cl',
		atomicNumber: 17,
		period: 3,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Argon',
		symbol: 'Ar',
		atomicNumber: 18,
		period: 3,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 4
	//
	//
	{
		name: 'Potassium',
		symbol: 'K',
		atomicNumber: 19,
		period: 4,
		group: 1,
		location: 'LEFT',
		color: 'orange',
	},
	{
		name: 'Calcium',
		symbol: 'Ca',
		atomicNumber: 20,
		period: 4,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},
	{
		name: 'Scandium',
		symbol: 'Sc',
		atomicNumber: 21,
		period: 4,
		group: 3,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Titanium',
		symbol: 'Ti',
		atomicNumber: 22,
		period: 4,
		group: 4,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Vanadium',
		symbol: 'V',
		atomicNumber: 23,
		period: 4,
		group: 5,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Chromium',
		symbol: 'Cr',
		atomicNumber: 24,
		period: 4,
		group: 6,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Manganese',
		symbol: 'Mn',
		atomicNumber: 25,
		period: 4,
		group: 7,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Iron',
		symbol: 'Fe',
		atomicNumber: 26,
		period: 4,
		group: 8,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Cobalt',
		symbol: 'Co',
		atomicNumber: 27,
		period: 4,
		group: 9,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Nickel',
		symbol: 'Ni',
		atomicNumber: 29,
		period: 4,
		group: 10,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Copper',
		symbol: 'Cu',
		atomicNumber: 29,
		period: 4,
		group: 11,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Zinc',
		symbol: 'Zn',
		atomicNumber: 30,
		period: 4,
		group: 12,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Silicon',
		symbol: 'Si',
		atomicNumber: 14,
		period: 4,
		group: 14,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Gallium',
		symbol: 'Ga',
		atomicNumber: 31,
		period: 4,
		group: 13,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Germanium',
		symbol: 'Ge',
		atomicNumber: 32,
		period: 4,
		group: 14,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Arsenic',
		symbol: 'As',
		atomicNumber: 33,
		period: 4,
		group: 15,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Selenium',
		symbol: 'Se',
		atomicNumber: 34,
		period: 4,
		group: 16,
		location: 'RIGHT',
		color: lightPurple,
	},
	{
		name: 'Bromine',
		symbol: 'Br',
		atomicNumber: 35,
		period: 4,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Krypton',
		symbol: 'Kr',
		atomicNumber: 36,
		period: 4,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 5
	//
	//
	{
		name: 'Rubidium',
		symbol: 'Rb',
		atomicNumber: 37,
		period: 5,
		group: 1,
		location: 'LEFT',
		color: 'orange',
	},
	{
		name: 'Strontium',
		symbol: 'Sr',
		atomicNumber: 38,
		period: 5,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},
	{
		name: 'Yttrium',
		symbol: 'Y',
		atomicNumber: 39,
		period: 5,
		group: 3,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Zirconium',
		symbol: 'Zr',
		atomicNumber: 40,
		period: 5,
		group: 4,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Niobium',
		symbol: 'Nb',
		atomicNumber: 41,
		period: 5,
		group: 5,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Molybendium',
		symbol: 'Mo',
		atomicNumber: 42,
		period: 5,
		group: 6,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Technetium',
		symbol: 'Tc',
		atomicNumber: 43,
		period: 5,
		group: 7,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Ruthenium',
		symbol: 'Ru',
		atomicNumber: 45,
		period: 5,
		group: 8,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Rhodium',
		symbol: 'Rh',
		atomicNumber: 27,
		period: 5,
		group: 9,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Palladium',
		symbol: 'Pd',
		atomicNumber: 46,
		period: 5,
		group: 10,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Silver',
		symbol: 'Ag',
		atomicNumber: 47,
		period: 5,
		group: 11,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Cadmium',
		symbol: 'Cd',
		atomicNumber: 48,
		period: 5,
		group: 12,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Indium',
		symbol: 'In',
		atomicNumber: 49,
		period: 5,
		group: 13,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Tin',
		symbol: 'Sn',
		atomicNumber: 50,
		period: 5,
		group: 14,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Antimony',
		symbol: 'Sb',
		atomicNumber: 51,
		period: 5,
		group: 15,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Tellurium',
		symbol: 'Te',
		atomicNumber: 52,
		period: 5,
		group: 16,
		location: 'RIGHT',
		color: 'lightGreen',
	},
	{
		name: 'Iodine',
		symbol: 'I',
		atomicNumber: 53,
		period: 5,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Xenon',
		symbol: 'Xe',
		atomicNumber: 54,
		period: 5,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 6
	//
	//
	{
		name: 'Cesium',
		symbol: 'Cs',
		atomicNumber: 55,
		period: 6,
		group: 1,
		location: 'LEFT',
		color: 'orange',
	},
	{
		name: 'Barium',
		symbol: 'Ba',
		atomicNumber: 56,
		period: 6,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},

	{
		name: 'Hafnium',
		symbol: 'Hf',
		atomicNumber: 56,
		period: 6,
		group: 4,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Tantalum',
		symbol: 'Ta',
		atomicNumber: 73,
		period: 6,
		group: 5,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Tungsten',
		symbol: 'W',
		atomicNumber: 74,
		period: 6,
		group: 6,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Rhenium',
		symbol: 'Re',
		atomicNumber: 75,
		period: 6,
		group: 7,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Osmium',
		symbol: 'Os',
		atomicNumber: 76,
		period: 6,
		group: 8,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Iridium',
		symbol: 'Ir',
		atomicNumber: 77,
		period: 6,
		group: 9,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Platinum',
		symbol: 'Pt',
		atomicNumber: 78,
		period: 6,
		group: 10,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Gold',
		symbol: 'Au',
		atomicNumber: 79,
		period: 6,
		group: 11,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Mercury',
		symbol: 'Hg',
		atomicNumber: 80,
		period: 6,
		group: 12,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Thallium',
		symbol: 'Tl',
		atomicNumber: 81,
		period: 6,
		group: 13,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Lead',
		symbol: 'Pb',
		atomicNumber: 82,
		period: 6,
		group: 14,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Bismuth',
		symbol: 'Bi',
		atomicNumber: 83,
		period: 6,
		group: 15,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Polonium',
		symbol: 'Po',
		atomicNumber: 84,
		period: 6,
		group: 16,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Astatine',
		symbol: 'At',
		atomicNumber: 85,
		period: 6,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Radon',
		symbol: 'Rn',
		atomicNumber: 86,
		period: 6,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},
	//
	//
	// Period 7
	//
	//
	{
		name: 'Francium',
		symbol: 'Fr',
		atomicNumber: 87,
		period: 7,
		group: 1,
		location: 'LEFT',
		color: 'orange',
	},
	{
		name: 'Radium',
		symbol: 'Ra',
		atomicNumber: 88,
		period: 7,
		group: 2,
		location: 'LEFT',
		color: 'yellow',
	},

	{
		name: 'Rutherfordium',
		symbol: 'Rf',
		atomicNumber: 104,
		period: 7,
		group: 4,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Dubnium',
		symbol: 'Db',
		atomicNumber: 105,
		period: 7,
		group: 5,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Seaborgium',
		symbol: 'Sg',
		atomicNumber: 106,
		period: 7,
		group: 6,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Bohrium',
		symbol: 'Bh',
		atomicNumber: 107,
		period: 7,
		group: 7,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Hassium',
		symbol: 'Hs',
		atomicNumber: 108,
		period: 7,
		group: 8,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Meitnerium',
		symbol: 'Mt',
		atomicNumber: 109,
		period: 7,
		group: 9,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Darmstadtium',
		symbol: 'Ds',
		atomicNumber: 110,
		period: 7,
		group: 10,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Roentgenium',
		symbol: 'Rg',
		atomicNumber: 111,
		period: 7,
		group: 11,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Copernicium',
		symbol: 'Cn',
		atomicNumber: 112,
		period: 7,
		group: 12,
		location: 'MIDDLE',
		color: lightBlue,
	},
	{
		name: 'Nihonium',
		symbol: 'Nh',
		atomicNumber: 113,
		period: 7,
		group: 13,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Flerovium',
		symbol: 'Fl',
		atomicNumber: 114,
		period: 7,
		group: 14,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Moscovium',
		symbol: 'Mc',
		atomicNumber: 115,
		period: 7,
		group: 15,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Livermorium',
		symbol: 'Lv',
		atomicNumber: 116,
		period: 7,
		group: 16,
		location: 'RIGHT',
		color: lightYellow,
	},
	{
		name: 'Tennessine',
		symbol: 'Ts',
		atomicNumber: 117,
		period: 7,
		group: 17,
		location: 'RIGHT',
		color: 'pink',
	},
	{
		name: 'Oganesson',
		symbol: 'Og',
		atomicNumber: 118,
		period: 7,
		group: 18,
		location: 'RIGHT',
		color: 'lightBlue',
	},

	//
	//
	// Lanthanides
	//
	//

	{
		name: 'Lanthanum',
		symbol: 'La',
		atomicNumber: 57,
		period: 8,
		group: 4,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Cerium',
		symbol: 'Ce',
		atomicNumber: 58,
		period: 8,
		group: 5,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Praseodymium',
		symbol: 'Pr',
		atomicNumber: 59,
		period: 8,
		group: 6,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Neodymium',
		symbol: 'Nd',
		atomicNumber: 60,
		period: 8,
		group: 7,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Promethium',
		symbol: 'Pm',
		atomicNumber: 61,
		period: 8,
		group: 8,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Samarium',
		symbol: 'Sm',
		atomicNumber: 62,
		period: 8,
		group: 9,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Europium',
		symbol: 'Eu',
		atomicNumber: 63,
		period: 8,
		group: 10,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Gadolinium',
		symbol: 'Gd',
		atomicNumber: 64,
		period: 8,
		group: 11,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Terbium',
		symbol: 'Tb',
		atomicNumber: 65,
		period: 8,
		group: 12,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Dysprosium',
		symbol: 'Dy',
		atomicNumber: 66,
		period: 8,
		group: 13,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Holmium',
		symbol: 'Ho',
		atomicNumber: 67,
		period: 8,
		group: 14,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Erbium',
		symbol: 'Er',
		atomicNumber: 68,
		period: 8,
		group: 15,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Thulium',
		symbol: 'Tm',
		atomicNumber: 69,
		period: 8,
		group: 16,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Ytterbium',
		symbol: 'Tb',
		atomicNumber: 70,
		period: 8,
		group: 17,
		location: 'RARE_EARTH',
		color: lightRed,
	},
	{
		name: 'Lutetium',
		symbol: 'Lu',
		atomicNumber: 71,
		period: 8,
		group: 18,
		location: 'RARE_EARTH',
		color: lightRed,
	},

	//
	//
	// Actinides
	//
	//

	{
		name: 'Actinium',
		symbol: 'Ac',
		atomicNumber: 89,
		period: 9,
		group: 4,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Thorium',
		symbol: 'Th',
		atomicNumber: 90,
		period: 9,
		group: 5,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Protactinium',
		symbol: 'Pa',
		atomicNumber: 91,
		period: 9,
		group: 6,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Uranium',
		symbol: 'U',
		atomicNumber: 92,
		period: 9,
		group: 7,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Neptunium',
		symbol: 'Np',
		atomicNumber: 93,
		period: 9,
		group: 8,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Plutonium',
		symbol: 'Pu',
		atomicNumber: 94,
		period: 9,
		group: 9,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Americium',
		symbol: 'Am',
		atomicNumber: 95,
		period: 9,
		group: 10,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Curium',
		symbol: 'Cm',
		atomicNumber: 96,
		period: 9,
		group: 11,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Berkelium',
		symbol: 'Bk',
		atomicNumber: 97,
		period: 9,
		group: 12,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Californium',
		symbol: 'Cf',
		atomicNumber: 98,
		period: 9,
		group: 13,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Einsteinium',
		symbol: 'Es',
		atomicNumber: 99,
		period: 9,
		group: 14,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Fermium',
		symbol: 'Fm',
		atomicNumber: 100,
		period: 9,
		group: 15,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Mendelevium',
		symbol: 'Md',
		atomicNumber: 101,
		period: 9,
		group: 16,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Nobelium',
		symbol: 'No',
		atomicNumber: 102,
		period: 9,
		group: 17,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
	{
		name: 'Lawrencium',
		symbol: 'Lr',
		atomicNumber: 103,
		period: 9,
		group: 18,
		location: 'RARE_EARTH',
		color: lightBrown,
	},
]
